variables:
  PROJECT_VERSION: "gitlabci"
  PROJECT_NAME: "openweather"
  PROJECT_IMAGE_NAME: "nexoss.agile4security.io:5000/a4s/bubble:2.9"
  PROJECT_BLOCK_ON_SECURITY_ISSUES: "false"
  PROJECT_LANGUAGES: "node"
  PROJECT_BUILD_IMAGE: "node:14"
  PROJECT_BUILD_SCRIPT: "npm install"
  PROJECT_BUILD_LIBS: ""
  PROJECT_BUILD_ARTIFACTS: "./node_modules"
  FORTIFY_SSC_URL: "http://ssc:8080"
  FORTIFY_ATTRIBUTES: ""
  FORTIFY_ISSUE_TEMPLATE: "SOGETI Issue Template"
  SAST_ENABLE: "true"
  SAST_EXCLUDES: ""
  SAST_FORTIFY_JVM_OPTIONS: "-Xmx4G"
  SAST_FORTIFY_TOUCHLESS_COMMAND: ""
  SAST_FORTIFY_HLA: "true"
  SAST_FORTIFY_JAVA_VERSION: ""
  SAST_FORTIFY_PHP_VERSION: ""
  SAST_FORTIFY_PYTHON_VERSION: ""
  SAST_FORTIFY_PASS_FAIL_POLICY: ""
  # full, partial or no
  SAST_FORTIFY_SCANCENTRAL_ENABLE: "no"
  SAST_FORTIFY_SCANCENTRAL_CONTROLLER_URL: ""
  SAST_FORTIFY_SCANCENTRAL_BUILD_TOOL: ""
  SAST_FORTIFY_SCANCENTRAL_BUILD_FILE: ""
  SAST_FORTIFY_SCANCENTRAL_WAIT_FOR_SCAN_COMPLETE: ""
  SAST_FORTIFY_SCANCENTRAL_POOL: ""
  OSS_ODC_ENABLE: ""
  OSS_ODC_EXCLUDES: ""
  OSS_ODC_PASS_FAIL_POLICY: ""
  OSS_ODT_ENABLE: ""
  OSS_ODT_DEPENDENCY_MANAGER: ""
  OSS_ODT_URL: ""
  OSS_ODT_PASS_FAIL_POLICY: ""
  OSS_NEXUS_IQ_ENABLE: ""
  OSS_NEXUS_IQ_STAGE: ""
  OSS_NEXUS_IQ_EXCLUDES: ""
  OSS_NEXUS_IQ_URL: ""
  OSS_NEXUS_IQ_PASS_FAIL_POLICY: ""
  CQ_SONARQUBE_ENABLE: ""
  CQ_SONARQUBE_URL: ""
  CQ_SONARQUBE_PASS_FAIL_POLICY: ""
  CIST_TRIVY_ENABLE: ""
  CIST_TRIVY_PASS_FAIL_POLICY: ""
  DAST_ACUNETIX_ENABLE: ""
  DAST_ACUNETIX_URL: ""
  DAST_ACUNETIX_SCAN_TYPE: ""
  DAST_ACUNETIX_WAIT_FOR_SCAN_COMPLETE: ""
  DAST_ACUNETIX_TARGET_ADDRESS: ""
  DAST_ACUNETIX_TARGET_DESCRIPTION: ""
  DAST_ACUNETIX_TARGET_CRITICALITY: ""
  DAST_ACUNETIX_PASS_FAIL_POLICY: ""

include:
  - project: "fmolina/gitlabcicd-secgates"
    ref: master
    file: ".gitlab-ci-base.yml"
