variables:
  PROJECT_VERSION: "Z2"
  PROJECT_NAME: "DEMOLAB-NODEJS"
  PROJECT_IMAGE_NAME: ""
  PROJECT_BLOCK_ON_SECURITY_ISSUES: "false"
  PROJECT_LANGUAGES: "node"
  PROJECT_BUILD_IMAGE: "node:14"
  PROJECT_BUILD_SCRIPT: "npm install"
  PROJECT_BUILD_LIBS: ""
  PROJECT_BUILD_ARTIFACTS: "./node_modules;./package.json;./package-lock.json"
  FORTIFY_SSC_URL: "https://ssc-train.kube.agile4security.io/"
  FORTIFY_ATTRIBUTES: ""
  FORTIFY_ISSUE_TEMPLATE: "" 
  SAST_FORTIFY_ENABLE: "true"
  SAST_FORTIFY_EXCLUDES: ""
  SAST_FORTIFY_JVM_OPTIONS: "-Xmx4G"
  SAST_FORTIFY_TOUCHLESS_COMMAND: ""
  SAST_FORTIFY_HLA: ""
  SAST_FORTIFY_JAVA_VERSION: ""
  SAST_FORTIFY_PHP_VERSION: ""
  SAST_FORTIFY_PYTHON_VERSION: ""
  SAST_FORTIFY_PASS_FAIL_POLICY: ""
  # full, partial or no
  SAST_FORTIFY_SCANCENTRAL_ENABLE: "full"
  SAST_FORTIFY_SCANCENTRAL_CONTROLLER_URL: "http://scancentral-controller.fortify-demo/scancentral-ctrl"
  SAST_FORTIFY_SCANCENTRAL_BUILD_TOOL: ""
  SAST_FORTIFY_SCANCENTRAL_BUILD_FILE: ""
  SAST_FORTIFY_SCANCENTRAL_WAIT_FOR_SCAN_COMPLETE: ""
  SAST_FORTIFY_SCANCENTRAL_POOL: ""
  OSS_ODC_ENABLE: "false"
  OSS_ODC_EXCLUDES: ""
  OSS_ODC_PASS_FAIL_POLICY: "[fortify priority order]:critical AND [analysis type]:OWASP_DEPCHECK"
  OSS_ODT_ENABLE: "false"
  OSS_ODT_DEPENDENCY_MANAGER: "npm"
  OSS_ODT_URL: "https://otrack.kube.agile4security.io/"
  OSS_ODT_URL_API: "https://otrack-api.kube.agile4security.io/"
  OSS_ODT_PASS_FAIL_POLICY: ""
  OSS_NEXUS_IQ_ENABLE: "false"
  OSS_NEXUS_IQ_STAGE: "release"
  OSS_NEXUS_IQ_EXCLUDES: ""
  OSS_NEXUS_IQ_URL: "https://iq.kube.agile4security.io/"
  OSS_NEXUS_IQ_PASS_FAIL_POLICY: "[fortify priority order]:medium AND [analysis type]:SONATYPE"
  CQ_SONARQUBE_ENABLE: "false"
  CQ_SONARQUBE_URL: "https://sonarq.kube.agile4security.io/"
  CQ_SONARQUBE_PASS_FAIL_POLICY: ""
  CIST_TRIVY_ENABLE: "false"
  CIST_TRIVY_PASS_FAIL_POLICY: ""

.general-tags:
  tags:
    - linux

workflow:
  rules:
    - changes:
        - "*.md"
        - "*.log"
        - "*.txt"
        - "/**/*.log"
        - "/**/*.txt"
        - "/**/*.md"
        - "Jenkinsfile"
        - "sonar-project.properties"
      when: never
    - when: always 


include:
  - project: "lab/sec-gates-git-lab-ci-demo"
    ref: master
    file: ".gitlab-ci-base.yml"
