workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /a4s/i
    - when: never

job1:
  stage: build
  script:
    - echo "This script executes after the global before_script."
    - curl www.google.com

job:
  before_script:
    - echo "Execute this script instead of the global before_script."
  script:
    - echo "This script executes after the job's `before_script`"
